### ISSUE TITLE
大佬麻烦帮忙看一下，出现了这个报错，处理消息失败: REVOKE 

### ISSUE THREAD

**Issue by AnCool-OvO** [sineom-1/revocation#1]
[DEBUG][2024-11-15 11:11:52][plugin_manager.py:190] - Plugin REVOCATION triggered by event Event.ON_RECEIVE_MESSAGE                                                 
[DEBUG][2024-11-15 11:11:52][revocation.py:199] - [Revocation] on_receive_message:                             
[ERROR][2024-11-15 11:11:52][revocation.py:195] - 处理消息失败: REVOKE 
@sineom-1

**Comment by sineom-1** [comment]
1. [自行修改代码参照](https://github.com/zhayujie/chatgpt-on-wechat/commit/5c5a4f3c09d1144f86a11417d9ccd84967881d30)
2. 使用我fork的dev分支
            `

**Comment by AnCool-OvO** [comment]
> 1. [自行修改代码参照](https://github.com/zhayujie/chatgpt-on-wechat/commit/5c5a4f3c09d1144f86a11417d9ccd84967881d30)
> 2. 使用我fork的dev分支
>    `

好的，已经可以使用了感谢大佬，就是好像发送的表情包没有防撤回了

**Comment by sineom-1** [comment]
表情包好像是47  PICTURE像的判定增加一项就好了

**Comment by AnCool-OvO** [comment]
> 表情包好像是47 PICTURE像的判定增加一项就好了

哈哈有点不是太懂，是像加VIDEO类型那样在加一个表情包的类型吗是

**Comment by sineom-1** [comment]
是的
